### ISSUE TITLE
Fresh built instance of Spoofax 3 Eclipse not working

### ISSUE THREAD

**Issue by Virtlink** [metaborg/spoofax-pie#103]
## Summary
When I create a fresh checkout of `devenv`, build an Eclipse instance using `./gradlew buildSpoofax3LwbEclipseInstallation`, and run it using `spoofax.pie/lwb.distrib/spoofax.lwb.eclipse.repository/build/eclipse-macosx-x86_64/Spoofax3.app/Contents/MacOS/eclipse`, then importing a Spoofax 3 project fails.

## What actually happened
This error was printed to the console:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-01-10 10:15:40.560 eclipse[44804:2124761] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-01-10 10:15:40.560 eclipse[44804:2124761] nil host used in call to allowsAnyHTTPSCertificateForHost:
[...]
2022-01-10 10:15:40.599 eclipse[44804:2124761] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-01-10 10:15:40.599 eclipse[44804:2124761] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-01-10 10:15:40.620 eclipse[44804:2124761] *** WARNING: Method convertPointToBase: in class NSView is deprecated on 10.7 and later. It should not be used in new applications.
2022-01-10 10:16:48.171 eclipse[44804:2127425] CheckForInstalledJavaRuntimes: Please visit http://www.java.com for information on installing java.
```

## Context
* Spoofax version: latest 0.16.17-develop
* Operating system & version: macOS 11.6
* Java version: OpenJDK Temurin-11.0.13+8

## Additional information
The log from `.metadata/.log` of the workspace directory:

```
!SESSION 2022-01-10 10:15:19.555 -----------------------------------------------
eclipse.buildId=4.19.0.I20210303-1800
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/daniel/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/daniel/.eclipse_keyring

!ENTRY org.eclipse.buildship.core 4 0 2022-01-10 10:15:20.678
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.buildship.core [61]
  Unresolved requirement: Import-Package: org.slf4j; version="1.7.2"

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.buildship.ui 4 0 2022-01-10 10:15:20.679
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.buildship.ui [63]
  Unresolved requirement: Require-Bundle: org.eclipse.buildship.core
    -> Bundle-SymbolicName: org.eclipse.buildship.core; bundle-version="3.1.5.v20210113-0929"; singleton:="true"
       org.eclipse.buildship.core [61]
         Unresolved requirement: Import-Package: org.slf4j; version="1.7.2"
  Unresolved requirement: Require-Bundle: org.gradle.toolingapi; bundle-version="[6.8.0,6.9.0)"
    -> Bundle-SymbolicName: org.gradle.toolingapi; bundle-version="6.8.0.v20210113-0929"
       org.gradle.toolingapi [313]
         Unresolved requirement: Import-Package: org.slf4j; version="1.7.2"

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.egit.core 4 0 2022-01-10 10:15:21.090
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.egit.core [117]
  Unresolved requirement: Import-Package: org.eclipse.jgit.api; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.jgit.api; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"; uses:="org.eclipse.jgit.transport,  org.eclipse.jgit.notes,  org.eclipse.jgit.dircache,  org.eclipse.jgit.lib,  org.eclipse.jgit.revwalk,  org.eclipse.jgit.treewalk.filter,  org.eclipse.jgit.diff,  org.eclipse.jgit.treewalk,  org.eclipse.jgit.util,  org.eclipse.jgit.submodule,  org.eclipse.jgit.api.errors,  org.eclipse.jgit.revwalk.filter,  org.eclipse.jgit.blame,  org.eclipse.jgit.merge"
       org.eclipse.jgit [226]
         Unresolved requirement: Import-Package: org.slf4j; version="[1.7.0,2.0.0)"
  Unresolved requirement: Import-Package: org.eclipse.jgit.annotations; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.jgit.annotations; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.egit.ui 4 0 2022-01-10 10:15:21.092
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.egit.ui [119]
  Unresolved requirement: Import-Package: org.eclipse.egit.core; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.egit.core; bundle-symbolic-name="org.eclipse.egit.core"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"; x-friends:="org.eclipse.egit.ui,  org.eclipse.egit.ui.test,  org.eclipse.egit.mylyn.ui,  org.eclipse.egit.gitflow.test,  org.eclipse.egit.gitflow.ui,  org.eclipse.mylyn.github.ui,  org.eclipse.mylyn.github.core,  org.eclipse.egit.core.junit"
       org.eclipse.egit.core [117]
         Unresolved requirement: Import-Package: org.eclipse.jgit.api; version="[5.11.0,5.12.0)"
           -> Export-Package: org.eclipse.jgit.api; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"; uses:="org.eclipse.jgit.transport,  org.eclipse.jgit.notes,  org.eclipse.jgit.dircache,  org.eclipse.jgit.lib,  org.eclipse.jgit.revwalk,  org.eclipse.jgit.treewalk.filter,  org.eclipse.jgit.diff,  org.eclipse.jgit.treewalk,  org.eclipse.jgit.util,  org.eclipse.jgit.submodule,  org.eclipse.jgit.api.errors,  org.eclipse.jgit.revwalk.filter,  org.eclipse.jgit.blame,  org.eclipse.jgit.merge"
              org.eclipse.jgit [226]
                Unresolved requirement: Import-Package: org.slf4j; version="[1.7.0,2.0.0)"
         Unresolved requirement: Import-Package: org.eclipse.jgit.annotations; version="[5.11.0,5.12.0)"
           -> Export-Package: org.eclipse.jgit.annotations; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"
  Unresolved requirement: Import-Package: org.eclipse.egit.core.attributes; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.egit.core.attributes; bundle-symbolic-name="org.eclipse.egit.core"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"; uses:="org.eclipse.jgit.lib"

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.jgit.archive 4 0 2022-01-10 10:15:21.129
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jgit.archive [227]
  Unresolved requirement: Import-Package: org.eclipse.jgit.lib; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.jgit.lib; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"; uses:="org.eclipse.jgit.transport,  org.eclipse.jgit.util.sha1,  org.eclipse.jgit.dircache,  org.eclipse.jgit.revwalk,  org.eclipse.jgit.internal.storage.file,  org.eclipse.jgit.attributes,  org.eclipse.jgit.events,  com.googlecode.javaewah,  org.eclipse.jgit.treewalk.filter,  org.eclipse.jgit.treewalk,  org.eclipse.jgit.util,  org.eclipse.jgit.submodule,  org.eclipse.jgit.util.time"
       org.eclipse.jgit [226]
         Unresolved requirement: Import-Package: org.slf4j; version="[1.7.0,2.0.0)"
  Unresolved requirement: Import-Package: org.eclipse.jgit.api; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.jgit.api; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"; uses:="org.eclipse.jgit.transport,  org.eclipse.jgit.notes,  org.eclipse.jgit.dircache,  org.eclipse.jgit.lib,  org.eclipse.jgit.revwalk,  org.eclipse.jgit.treewalk.filter,  org.eclipse.jgit.diff,  org.eclipse.jgit.treewalk,  org.eclipse.jgit.util,  org.eclipse.jgit.submodule,  org.eclipse.jgit.api.errors,  org.eclipse.jgit.revwalk.filter,  org.eclipse.jgit.blame,  org.eclipse.jgit.merge"

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.jgit.http.apache 4 0 2022-01-10 10:15:21.130
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jgit.http.apache [229]
  Unresolved requirement: Import-Package: org.eclipse.jgit.annotations; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.jgit.annotations; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"
       org.eclipse.jgit [226]
         Unresolved requirement: Import-Package: org.slf4j; version="[1.7.0,2.0.0)"
  Unresolved requirement: Import-Package: org.eclipse.jgit.nls; version="[5.11.0,5.12.0)"
    -> Export-Package: org.eclipse.jgit.nls; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="5.11.0.202103091610-r"; version="5.11.0"

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.jgit.ssh.apache 4 0 2022-01-10 10:15:21.132
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jgit.ssh.apache [230]
  Unresolved requirement: Import-Package: org.apache.sshd.agent; version="[2.6.0,2.7.0)"
    -> Export-Package: org.apache.sshd.agent; bundle-symbolic-name="org.apache.sshd.osgi"; bundle-version="2.6.0.v20210201-2003"; version="2.6.0"; uses:="org.apache.sshd.common,org.apache.sshd.common.channel,org.apache.sshd.common.session"
       org.apache.sshd.osgi [48]
         Unresolved requirement: Import-Package: org.apache.tomcat.jni; version="5.5.0"; resolution:="optional"
         Unresolved requirement: Import-Package: org.bouncycastle.openssl; version="[1.65.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.bouncycastle.openssl.jcajce; version="[1.65.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.slf4j; version="[1.7.0,2.0.0)"
  Unresolved requirement: Import-Package: org.apache.sshd.client; version="[2.6.0,2.7.0)"
    -> Export-Package: org.apache.sshd.client; bundle-symbolic-name="org.apache.sshd.osgi"; bundle-version="2.6.0.v20210201-2003"; version="2.6.0"; uses:="org.apache.sshd.client.auth,org.apache.sshd.client.auth.keyboard,org.apache.sshd.client.auth.password,org.apache.sshd.client.config.hosts,org.apache.sshd.client.config.keys,org.apache.sshd.client.future,org.apache.sshd.client.keyverifier,org.apache.sshd.client.session,org.apache.sshd.client.simple,org.apache.sshd.common,org.apache.sshd.common.auth,org.apache.sshd.common.channel,org.apache.sshd.common.compression,org.apache.sshd.common.config.keys,org.apache.sshd.common.future,org.apache.sshd.common.helpers,org.apache.sshd.common.io,org.apache.sshd.common.kex,org.apache.sshd.common.keyprovider,org.apache.sshd.common.session,org.apache.sshd.common.signature"

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by Gohla** [comment]
These logs contain no mention of Spoofax, although these "Could not resolve module" errors probably should not be there. How does it fail to import a Spoofax project? How do you import it? Did you follow the steps from https://www.spoofax.dev/spoofax-pie/develop/tutorial/install/ for setting up Eclipse?
