### ISSUE TITLE
Internal error occurs during SPT editor update related to non-associative operators

### ISSUE THREAD

**Issue by RvanBaarle** [metaborg/spoofax-pie#19]
When writing a test for a `non-assoc` expression, if there is no whitespace after an expression, an exception is thrown on editor update.

An example test would be:

```
module test

language example

test hello [[ Hello == World == World]] parse fails
```

For the following small language:
```
module start

context-free start-symbols

  Start

context-free sorts

  Start
  Word
  Exp

context-free syntax

  Start.Empty = <>
  Start.Program = Exp
  Word.Hello = "Hello"
  Word.World = "World"
  Exp.Eq = Exp "==" Exp {non-assoc}
  Exp.Word = Word

lexical syntax

  LAYOUT = [\ \n\v\f\r]

context-free restrictions

  LAYOUT? -/- [\ \n\v\f\r]
```

This results in the following stack trace:
```
java.lang.IllegalArgumentException: The end offset 24 must be greater than or equal to the start offset 45
	at mb.common.region.Region.<init>(Region.java:24)
	at mb.common.region.Region.<init>(Region.java:37)
	at mb.common.region.Region.fromOffsets(Region.java:58)
	at mb.jsglr.common.FragmentedOriginLocationFixer.lambda$fixOriginLocations$1(FragmentedOriginLocationFixer.java:109)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at mb.common.message.KeyedMessages.lambda$map$1(KeyedMessages.java:201)
	at mb.common.util.MultiMap.forEach(MultiMap.java:169)
	at mb.common.util.MultiMapView.forEachEntry(MultiMapView.java:140)
	at mb.common.message.KeyedMessages.map(KeyedMessages.java:200)
	at mb.jsglr.common.FragmentedOriginLocationFixer.lambda$fixOriginLocations$2(FragmentedOriginLocationFixer.java:90)
	at mb.common.text.Texts$LambdaCases.fragmentedString(Texts.java:66)
	at mb.common.text.Texts$FragmentedString_.match(Texts.java:103)
	at mb.common.text.Texts$CaseOfMatchers$TotalMatcher_FragmentedString.fragmentedString(Texts.java:228)
	at mb.jsglr.common.FragmentedOriginLocationFixer.fixOriginLocations(FragmentedOriginLocationFixer.java:41)
	at mb.jsglr2.common.Jsglr2Parser.parse(Jsglr2Parser.java:72)
	at mb.Example.ExampleParser.parse(%2Flayoutdependent%2Fbuild%2Fgenerated%2Fsources%2Flanguage%2Fmb%2FExample%2FExampleParser.java:19)
	at mb.Example.task.ExampleParse.parse(%2Flayoutdependent%2Fbuild%2Fgenerated%2Fsources%2Fadapter%2Fmb%2FExample%2Ftask%2FExampleParse.java:50)
	at mb.jsglr.pie.JsglrParseTaskDef.exec(JsglrParseTaskDef.java:100)
	at mb.jsglr.pie.JsglrParseTaskDef.exec(JsglrParseTaskDef.java:23)
	at mb.pie.api.Task.exec(Task.java:56)
	at mb.pie.runtime.exec.TaskExecutor.execInternal(TaskExecutor.java:110)
	at mb.pie.runtime.exec.TaskExecutor.exec(TaskExecutor.java:81)
	at mb.pie.runtime.exec.TopDownRunner.exec(TopDownRunner.java:195)
	at mb.pie.runtime.exec.TopDownRunner.executeOrGetExisting(TopDownRunner.java:167)
	at mb.pie.runtime.exec.TopDownRunner.require(TopDownRunner.java:80)
	at mb.pie.runtime.exec.TopDownRunner.requireInitial(TopDownRunner.java:59)
	at mb.pie.runtime.MixedSessionImpl.lambda$requireWithoutObserving$2(MixedSessionImpl.java:103)
	at mb.pie.runtime.SessionImpl.handleException(SessionImpl.java:149)
	at mb.pie.runtime.MixedSessionImpl.requireWithoutObserving(MixedSessionImpl.java:103)
	at mb.pie.runtime.MixedSessionImpl.requireWithoutObserving(MixedSessionImpl.java:97)
	at mb.Example.ExampleInstance.testParse(%2Flayoutdependent%2Fbuild%2Fgenerated%2Fsources%2Fadapter%2Fmb%2FExample%2FExampleInstance.java:164)
	at mb.spt.expectation.ParseExpectation.evaluate(ParseExpectation.java:52)
	at mb.spt.task.SptCheck.runTests(SptCheck.java:162)
	at mb.spt.task.SptCheck.lambda$runTests$1(SptCheck.java:146)
	at mb.common.result.Result.ifThrowingElse(Result.java:150)
	at mb.spt.task.SptCheck.runTests(SptCheck.java:145)
	at mb.spt.task.SptCheck.lambda$exec$0(SptCheck.java:110)
	at mb.common.result.Result.ifThrowingElse(Result.java:150)
	at mb.spt.task.SptCheck.exec(SptCheck.java:108)
	at mb.spt.task.SptCheck.exec(SptCheck.java:40)
	at mb.pie.api.Task.exec(Task.java:56)
	at mb.pie.runtime.exec.TaskExecutor.execInternal(TaskExecutor.java:110)
	at mb.pie.runtime.exec.TaskExecutor.exec(TaskExecutor.java:81)
	at mb.pie.runtime.exec.BottomUpRunner.exec(BottomUpRunner.java:354)
	at mb.pie.runtime.exec.BottomUpRunner.execAndSchedule(BottomUpRunner.java:118)
	at mb.pie.runtime.exec.BottomUpRunner.execScheduled(BottomUpRunner.java:110)
	at mb.pie.runtime.exec.BottomUpRunner.requireInitial(BottomUpRunner.java:75)
	at mb.pie.runtime.MixedSessionImpl.lambda$updateAffectedBy$0(MixedSessionImpl.java:65)
	at mb.pie.runtime.SessionImpl.handleException(SessionImpl.java:161)
	at mb.pie.runtime.MixedSessionImpl.updateAffectedBy(MixedSessionImpl.java:65)
	at mb.spoofax.eclipse.pie.PieRunner.updateAffectedBy(PieRunner.java:442)
	at mb.spoofax.eclipse.pie.PieRunner.addOrUpdateEditor(PieRunner.java:128)
	at mb.spoofax.eclipse.editor.EditorUpdateJob.update(EditorUpdateJob.java:89)
	at mb.spoofax.eclipse.editor.EditorUpdateJob.run(EditorUpdateJob.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Note that adding some whitespace after the test will make the test work as intended:
```
test hello [[ Hello == World == World ]] parse fails
```

Using `left`, `right` or nothing instead of `non-assoc` will also not cause an internal error.

**Comment by Gohla** [comment]
Nice catch again, fixed in https://github.com/metaborg/spoofax-pie/commit/b0b8c2bd616237c569b6d9db6ef45e2cb65089c6.
