### ISSUE TITLE
Resolve out of bounds

### ISSUE THREAD

**Issue by JonathanBrouwer** [metaborg/spoofax-pie#82]
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at mb.common.util.ListView.get(ListView.java:69)
	at mb.spt.expectation.ResolveExpectation.evaluate(ResolveExpectation.java:39)
	at mb.spt.task.SptCheck.runTests(SptCheck.java:163)
	at mb.spt.task.SptCheck.lambda$runTests$1(SptCheck.java:147)
	at mb.common.result.Result.ifThrowingElse(Result.java:235)
	at mb.spt.task.SptCheck.runTests(SptCheck.java:146)
	at mb.spt.task.SptCheck.lambda$exec$0(SptCheck.java:111)
	at mb.common.result.Result.ifThrowingElse(Result.java:235)
	at mb.spt.task.SptCheck.exec(SptCheck.java:109)
	at mb.spt.task.SptCheck.exec(SptCheck.java:41)
	at mb.pie.api.Task.exec(Task.java:56)
	at mb.pie.runtime.exec.TaskExecutor.execInternal(TaskExecutor.java:128)
	at mb.pie.runtime.exec.TaskExecutor.exec(TaskExecutor.java:85)
	at mb.pie.runtime.exec.BottomUpRunner.exec(BottomUpRunner.java:369)
	at mb.pie.runtime.exec.BottomUpRunner.execAndSchedule(BottomUpRunner.java:133)
	at mb.pie.runtime.exec.BottomUpRunner.execScheduled(BottomUpRunner.java:120)
	at mb.pie.runtime.exec.BottomUpRunner.requireInitial(BottomUpRunner.java:83)
	at mb.pie.runtime.MixedSessionImpl.lambda$updateAffectedBy$0(MixedSessionImpl.java:70)
	at mb.pie.runtime.SessionImpl.handleException(SessionImpl.java:160)
	at mb.pie.runtime.MixedSessionImpl.updateAffectedBy(MixedSessionImpl.java:70)
	at mb.spoofax.eclipse.pie.PieRunner.updateAffectedBy(PieRunner.java:453)
	at mb.spoofax.eclipse.pie.PieRunner.addOrUpdateEditor(PieRunner.java:132)
	at mb.spoofax.eclipse.editor.EditorUpdateJob.update(EditorUpdateJob.java:97)
	at mb.spoofax.eclipse.editor.EditorUpdateJob.run(EditorUpdateJob.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Gohla** [comment]
Fixed by https://github.com/metaborg/spoofax-pie/commit/8e26e50cd7dc84c8fff5d2ae238bdf46c80e2c06
